service: sls-amcart
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  stage: dev
  environment:
    AWS_REGION_NAME: "ap-south-1"
    USER_POOL_ID: ""
    APP_CLIENT_ID: ""

plugins:
  - serverless-python-requirements

package:
  patterns:
    - '!node_modules/**'
    - '!tmp/**'
    - '!.git/**'
    - '!__pycache__'
    - '!auth'
    - '!src'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'


custom:
  pythonRequirements:
   dockerizePip: non-linux
   zip: true
   useDownloadCache: false
   useStaticCache: false
functions:
  python-authorizer:
    handler: handler.main

